name: OpenAPI spec validation action

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OpenAPI spec validation
        uses: stoplightio/spectral-action@v0.8.12
        with:
          file_glob: 'service/openapi.yaml'
