name: OpenAPI spec validation action

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run OpenAPI spec validation
        run: |
          docker run --rm -v $PWD:/spec redocly/cli lint ./service/openapi.yaml
          echo "{exit_code}={$?}" >> $GITHUB_STATE